# Generated by Django 4.1.7 on 2023-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='conclusion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='conclusion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
