# Generated by Django 4.1.7 on 2023-03-03 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_book_conclusion_date_course_conclusion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='award',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('fk_daily_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.daily_objective')),
            ],
        ),
    ]
