# Generated by Django 4.1.7 on 2023-03-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_rule_award_logbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.category')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('conclusion_date', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('reward', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='award',
            new_name='reward',
        ),
        migrations.AddField(
            model_name='goal',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.user'),
        ),
        migrations.AddField(
            model_name='category_record',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.user'),
        ),
    ]
