# Generated by Django 4.1.7 on 2023-03-14 02:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_category_category_record_goal_user_delete_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='fk_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='record.user'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
