# Generated by Django 4.1.7 on 2023-03-16 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_rename_logbook_daily_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='reward',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goal',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
