# Generated by Django 4.1.7 on 2023-03-23 00:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_category_reward_alter_goal_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_record',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.datetime.today)),
                ('conclusion_date', models.DateField(blank=True, null=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.user')),
            ],
        ),
    ]
